version: "3.7"

services:
    web:
        build: .
        ports:
            - 8082:8080
        command: sh -c "npm install && npm run dev"
        volumes:
            - ".:/app"
        environment:
            HOST: 0.0.0.0